###
# получение списка всех категорий

GET localhost:8080/category/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZTIyIiwiaWF0IjoxNjk1NjYyMjAxLCJleHAiOjE2OTU3NDg2MDF9.izAkN95R2oVciZHk2yvmGdGYwup3Kbl0UluovIl5RNg