###
# Добавляет блюдо

POST localhost:8080/dishes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZTIyIiwiaWF0IjoxNjk1NjY0OTIxLCJleHAiOjE2OTU3NTEzMjF9.F4bBXIRsCYvpg12F0nT9f_7x4GTVG8CacbNC3iVn6xM
Content-Type: application/json

{
  "name": "ПП7",
  "urlImage": "ваf",
  "category": {
    "id": 3
  },
  "price": 100,
  "weight": 100
}

###
# Получает блюда в филиале

GET localhost:8080/dishes/all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZTIyIiwiaWF0IjoxNjk1NjY0OTIxLCJleHAiOjE2OTU3NTEzMjF9.F4bBXIRsCYvpg12F0nT9f_7x4GTVG8CacbNC3iVn6xM

###
# Получает блюдо по id

GET localhost:8080/dishes/5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZTIyIiwiaWF0IjoxNjk1NjY0OTIxLCJleHAiOjE2OTU3NTEzMjF9.F4bBXIRsCYvpg12F0nT9f_7x4GTVG8CacbNC3iVn6xM

###
# Удаляет блюдо в филиале

DELETE localhost:8080/dishes/5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZTIyIiwiaWF0IjoxNjk1NjY0OTIxLCJleHAiOjE2OTU3NTEzMjF9.F4bBXIRsCYvpg12F0nT9f_7x4GTVG8CacbNC3iVn6xM
