###
# Добавляет заказ

POST localhost:8080/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZTIyIiwiaWF0IjoxNjk1NzA1MzYyLCJleHAiOjE2OTU3OTE3NjJ9.IIHVs6JMtG_kWe6RPvx1AesBklcA1mTQK0NA2lNW0vo
Content-Type: application/json

{
  "clientId": 1,
  "clientName": "fgh",
  "clientPhoneNumber": 4563,
  "employee": {
    "id": 1
  },
  "address": "dfg",
  "statusOrders": "IN_PROCESS",
  "deadline": "2020-12-20 12:12:01"
}

###
# Обновляет заказ

PUT localhost:8080/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZTIyIiwiaWF0IjoxNjk1NzA1MzYyLCJleHAiOjE2OTU3OTE3NjJ9.IIHVs6JMtG_kWe6RPvx1AesBklcA1mTQK0NA2lNW0vo
Content-Type: application/json

{
  "clientId": 1,
  "clientName": "fgh",
  "clientPhoneNumber": 4563,
  "employee": {
    "id": 1
  },
  "address": "dfg",
  "statusOrders": "IN_PROCESS",
  "deadline": "2020-12-20 12:12:01"
}

###
# Получает заказы из очереди на рассмотрение

GET localhost:8080/orders/all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZTIyIiwiaWF0IjoxNjk1NzA1MzYyLCJleHAiOjE2OTU3OTE3NjJ9.IIHVs6JMtG_kWe6RPvx1AesBklcA1mTQK0NA2lNW0vo

###
# Получает заказ по id

GET localhost:8080/orders/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZTIyIiwiaWF0IjoxNjk1NzA1MzYyLCJleHAiOjE2OTU3OTE3NjJ9.IIHVs6JMtG_kWe6RPvx1AesBklcA1mTQK0NA2lNW0vo
