###
# Обновляет статус заказа

PUT localhost:8080/orders/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZSIsImlhdCI6MTY5Njg3Nzc1NiwiZXhwIjoxNjk2OTY0MTU2fQ.kRo789TICtGiOphHSFMin7N2nwdrXSQscRTJ_gBQ38E
Content-Type: application/json

{
  "status": "REVIEW"
}

###
# Получает заказы со статусами на рассмотрении и в процессе

GET localhost:8080/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZSIsImlhdCI6MTY5Njg3Nzc1NiwiZXhwIjoxNjk2OTY0MTU2fQ.kRo789TICtGiOphHSFMin7N2nwdrXSQscRTJ_gBQ38E

###
# Отменяет заказ

PUT localhost:8080/orders/1/cancel
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZSIsImlhdCI6MTY5Njg3Nzc1NiwiZXhwIjoxNjk2OTY0MTU2fQ.kRo789TICtGiOphHSFMin7N2nwdrXSQscRTJ_gBQ38E
Content-Type: application/json

{
  "message": "!У клиента имя не грузинское, так нельзя."
}