server:
  error:
    include-message: always
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: restaurant_service
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/restaurant-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: login-app
      principle-attribute: preferred_username
  email-address:
    address: mish.uxin2012@yandex.ru
    password: mklvtcplyygdzuzt
  order-service:
    url: localhost:8083/
    name: orderService

api-config:
  url:
    keycloakTokenUrl: http://localhost:8080/realms/restaurant-realm/protocol/openid-connect/token
    keycloakCreateUserUrl: http://localhost:8080/admin/realms/restaurant-realm/users
    keycloakUpdateUserUrl: http://localhost:8080/admin/realms/restaurant-realm/users/
    KeyCloakOrderToken: http://localhost:8080/realms/order-realm/protocol/openid-connect/token
